// Package middleware provides HTTP middleware for the CBDC API server.
// This file defines typed context keys to avoid the common mistake of
// using plain strings as context keys, which can silently collide across packages.
package middleware

// ContextKey is the exported type for context keys used by this package.
// Tests and other packages that need to inject values into the context
// (e.g., for testing middleware without a full HTTP stack) use this type.
type ContextKey = contextKey

// contextKey is the underlying private type — prevents collisions with
// other packages that might use the same string values as plain interface{} keys.
type contextKey string

const (
	// ContextKeyUserID holds the authenticated user's UUID string.
	ContextKeyUserID contextKey = "user_id"

	// ContextKeyUserRole holds the authenticated user's role: user|merchant|admin.
	ContextKeyUserRole contextKey = "user_role"

	// ContextKeyWalletID holds the authenticated user's primary wallet UUID string.
	ContextKeyWalletID contextKey = "wallet_id"

	// ContextKeyRequestID holds the per-request trace ID (from X-Request-ID header
	// or generated by chi's RequestID middleware).
	ContextKeyRequestID contextKey = "request_id"
)
